# Generated by Django 5.2.4 on 2025-11-24 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_type', models.CharField(choices=[('HIGH', '고등학교'), ('UNIV_2_3', '대학교(2,3년)'), ('UNIV_4', '대학교(4년)'), ('GRAD_MS', '대학원(석사)'), ('GRAD_PHD', '대학원(박사)')], max_length=20, verbose_name='학교구분')),
                ('school_name', models.CharField(max_length=100, verbose_name='학교명')),
                ('is_transfer', models.BooleanField(default=False, verbose_name='편입 여부')),
                ('start_year_month', models.CharField(blank=True, max_length=7, verbose_name='입학연월')),
                ('end_year_month', models.CharField(blank=True, max_length=7, verbose_name='졸업연월')),
                ('status', models.CharField(choices=[('ENROLLED', '재학중'), ('GRADUATED', '졸업'), ('COMPLETED', '수료'), ('EXPECTED', '졸업예정'), ('DROPPED', '중퇴'), ('LEAVE', '휴학'), ('WITHDRAWN', '자퇴')], default='ENROLLED', max_length=20, verbose_name='졸업 여부')),
                ('major_type', models.CharField(blank=True, choices=[('MAJOR', '주전공'), ('MINOR', '부전공'), ('DOUBLE', '이중전공'), ('SECOND', '복수전공')], max_length=20, verbose_name='전공구분')),
                ('major_name', models.CharField(blank=True, max_length=100, verbose_name='전공명')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='학점')),
                ('gpa_scale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='총점')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='하드스킬명')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='스킬코드')),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='카테고리명')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='링크명')),
                ('url', models.URLField(verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='소프트스킬명')),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='직무명')),
                ('group', models.CharField(choices=[('dev', '개발'), ('design', '디자인'), ('pm', '기획/프로덕트'), ('biz', '비즈니스/경영'), ('etc', '기타')], default='dev', max_length=16, verbose_name='분야')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_roles', to='profiles.jobcategory', verbose_name='직무 카테고리')),
            ],
            options={
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobHardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.hardskill')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='JobSoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=50, verbose_name='표시 이름')),
                ('bio', models.TextField(blank=True, verbose_name='소개')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='아바타')),
                ('website', models.URLField(blank=True, verbose_name='웹사이트')),
                ('full_name', models.CharField(blank=True, max_length=50, verbose_name='이름')),
                ('github_linked', models.BooleanField(default=False, verbose_name='깃허브 연동 여부')),
                ('level', models.CharField(choices=[('student', '학생'), ('newgrad', '신입'), ('experienced', '경력')], default='student', max_length=12, verbose_name='레벨')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.jobrole', verbose_name='직무')),
            ],
        ),
    ]
