# Generated by Django 5.2.4 on 2025-11-24 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='하드스킬명')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='스킬코드')),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='카테고리명')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='링크 이름')),
                ('url', models.URLField(verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='소프트스킬명')),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='직무명')),
                ('group', models.CharField(choices=[('dev', '개발'), ('design', '디자인'), ('pm', '기획/프로덕트'), ('biz', '비즈니스/경영'), ('etc', '기타')], default='dev', max_length=16, verbose_name='분야')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_roles', to='profiles.jobcategory', verbose_name='직무 카테고리')),
            ],
            options={
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobHardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.hardskill')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='JobSoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50, verbose_name='이름')),
                ('bio', models.TextField(blank=True, verbose_name='소개')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='아바타')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='연락 이메일')),
                ('school_name', models.CharField(blank=True, max_length=120, verbose_name='학교명')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='입학 연월')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='졸업 연월')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.jobrole', verbose_name='직무')),
            ],
        ),
    ]
