# Generated by Django 5.2.4 on 2025-11-24 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilelink',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='jobsoftskill',
            name='soft_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.softskill'),
        ),
        migrations.AlterUniqueTogether(
            name='jobhardskill',
            unique_together={('job_role', 'hard_skill')},
        ),
        migrations.AlterUniqueTogether(
            name='jobsoftskill',
            unique_together={('job_role', 'soft_skill')},
        ),
    ]
