# Generated by Django 5.2.4 on 2025-11-24 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='학점'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gpa_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='총점'),
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='졸업 여부'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_role_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='직무명(직접 입력)'),
        ),
        migrations.CreateModel(
            name='ProfileMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_type', models.CharField(blank=True, choices=[('major', '주전공'), ('double', '복수전공'), ('minor', '부전공'), ('other', '기타')], max_length=20, verbose_name='전공 구분')),
                ('major_name', models.CharField(max_length=120, verbose_name='전공명')),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
