# Generated by Django 5.2.4 on 2025-08-22 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='직무명')),
                ('group', models.CharField(choices=[('dev', '개발'), ('design', '디자인'), ('pm', '기획/프로덕트'), ('biz', '비즈니스/경영'), ('etc', '기타')], default='dev', max_length=16, verbose_name='분야')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_linked',
            field=models.BooleanField(default=False, verbose_name='깃허브 연동 여부'),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('student', '학생'), ('newgrad', '신입'), ('experienced', '경력')], default='student', max_length=12, verbose_name='레벨'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.jobrole', verbose_name='직무'),
        ),
    ]
