# Generated by Django 5.2.4 on 2025-11-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_gpa_profile_gpa_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gpa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='학점'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gpa_total',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='총점'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='graduation_status',
            field=models.CharField(blank=True, choices=[('재학중', '재학중'), ('졸업', '졸업'), ('수료', '수료'), ('졸업예정', '졸업예정'), ('중퇴', '중퇴'), ('휴학', '휴학'), ('자퇴', '자퇴')], max_length=30, verbose_name='졸업 여부'),
        ),
    ]
