# Generated by Django 5.2.4 on 2025-10-27 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_seed_jobroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='하드스킬명')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='스킬코드')),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='카테고리명')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='소프트스킬명')),
            ],
        ),
        migrations.AddField(
            model_name='jobrole',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_roles', to='profiles.jobcategory', verbose_name='직무 카테고리'),
        ),
        migrations.CreateModel(
            name='JobHardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.hardskill')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.jobrole')),
            ],
            options={
                'unique_together': {('job_role', 'hard_skill')},
            },
        ),
        migrations.CreateModel(
            name='JobSoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.jobrole')),
                ('soft_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.softskill')),
            ],
            options={
                'unique_together': {('job_role', 'soft_skill')},
            },
        ),
    ]
