# Generated by Django 5.2.4 on 2025-11-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='활동명')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='활동 시작일')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='활동 종료일')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='역할 및 담당')),
                ('description', models.TextField(blank=True, verbose_name='활동 소개')),
                ('outcome', models.TextField(blank=True, verbose_name='성과')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='activity_attachments/', verbose_name='첨부파일')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='주제')),
                ('host', models.CharField(blank=True, max_length=200, verbose_name='주최/주관')),
                ('work_title', models.CharField(blank=True, max_length=200, verbose_name='출품작/프로젝트명')),
                ('participation_type', models.CharField(blank=True, choices=[('team', '팀'), ('individual', '개인')], max_length=20, verbose_name='참여 형태')),
                ('is_awarded', models.BooleanField(default=False, verbose_name='수상 여부')),
                ('award_detail', models.CharField(blank=True, max_length=200, verbose_name='수상 내역')),
                ('situation', models.TextField(blank=True, verbose_name='상황(Situation)')),
                ('task_detail', models.TextField(blank=True, verbose_name='과제(Task)')),
                ('action_detail', models.TextField(blank=True, verbose_name='행동(Action)')),
                ('result_detail', models.TextField(blank=True, verbose_name='결과(Result)')),
                ('takeaway', models.TextField(blank=True, verbose_name='교훈(Takeaway)')),
                ('organization', models.CharField(blank=True, max_length=120, verbose_name='소속 팀/회사')),
                ('plan_count', models.PositiveSmallIntegerField(default=0)),
                ('design_count', models.PositiveSmallIntegerField(default=0)),
                ('dev_count', models.PositiveSmallIntegerField(default=0)),
                ('learned', models.TextField(blank=True, verbose_name='배운 점')),
                ('link_url', models.URLField(blank=True, verbose_name='링크 첨부')),
                ('status', models.CharField(choices=[('in_progress', '진행 중'), ('highlight', '주요 스펙'), ('completed', '완료')], default='in_progress', max_length=20, verbose_name='보드 상태')),
                ('board_order', models.PositiveIntegerField(default=0, verbose_name='보드 정렬')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityHardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('level_description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='메모 내용')),
                ('date', models.DateField(auto_now_add=True, verbose_name='날짜')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='역할명')),
                ('count', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('level_description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards_name', models.CharField(max_length=200, verbose_name='수상명')),
                ('awards_grade', models.CharField(blank=True, max_length=100, verbose_name='등급/수상내역')),
                ('achievement_date', models.DateField(verbose_name='수상일자')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='award_attachments/', verbose_name='첨부파일')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200, verbose_name='자격증명')),
                ('achievement_date', models.DateField(verbose_name='취득일자')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='만료일자')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='발급기관')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='certification_attachments/', verbose_name='첨부파일')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=100, verbose_name='언어명')),
                ('lang_level', models.CharField(max_length=50, verbose_name='수준')),
                ('achievement_date', models.DateField(blank=True, null=True, verbose_name='취득일자')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='foreignlang_attachments/', verbose_name='첨부파일')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_category', models.CharField(max_length=100, verbose_name='경험 카테고리')),
                ('nation', models.CharField(max_length=100, verbose_name='국가')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('language', models.CharField(blank=True, max_length=100, verbose_name='사용 언어')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='globalexp_attachments/', verbose_name='첨부파일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그 이름')),
                ('kind', models.CharField(choices=[('soft', '소프트'), ('hard', '하드'), ('job', '직무')], default='soft', max_length=10, verbose_name='속성')),
            ],
        ),
    ]
