# Generated by Django 5.2.4 on 2025-07-17 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='활동명')),
                ('role', models.CharField(max_length=100, verbose_name='역할')),
                ('field', models.CharField(max_length=100, verbose_name='분야')),
                ('date', models.DateField(verbose_name='활동 일자')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='연관 스킬')),
                ('role_detail', models.TextField(blank=True, verbose_name='어떤 역할을 맡았나요?')),
                ('process_detail', models.TextField(blank=True, verbose_name='과정 설명')),
                ('learn_detail', models.TextField(blank=True, verbose_name='무엇을 배웠나요?')),
                ('result_detail', models.TextField(blank=True, verbose_name='어떤 성과가 있었나요?')),
                ('thumbnail', models.URLField(blank=True, verbose_name='썸네일 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
