# Generated by Django 5.2.4 on 2025-08-15 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-updated_at', '-period_start']},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='summary',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='field',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='learn_detail',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='process_detail',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='result_detail',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='role_detail',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='activity',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='activity_attachments/', verbose_name='첨부파일'),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, verbose_name='활동 소개'),
        ),
        migrations.AddField(
            model_name='activity',
            name='outcome',
            field=models.TextField(blank=True, verbose_name='성과'),
        ),
        migrations.AddField(
            model_name='activity',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='활동 종료일'),
        ),
        migrations.AddField(
            model_name='activity',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='활동 시작일'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='role',
            field=models.CharField(blank=True, max_length=200, verbose_name='역할 및 담당'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivityMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='메모 내용')),
                ('date', models.DateField(auto_now_add=True, verbose_name='날짜')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='activity.activity')),
            ],
        ),
    ]
