# Generated by Django 5.2.4 on 2025-11-24 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activity.activitycategory'),
        ),
        migrations.AddField(
            model_name='activityhardskill',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hard_skill_links', to='activity.activity'),
        ),
        migrations.AddField(
            model_name='activityhardskill',
            name='hard_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_links', to='profiles.hardskill'),
        ),
        migrations.AddField(
            model_name='activitymemo',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='activity.activity'),
        ),
        migrations.AddField(
            model_name='activityrole',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='activity.activity'),
        ),
        migrations.AddField(
            model_name='activitysoftskill',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_skill_links', to='activity.activity'),
        ),
        migrations.AddField(
            model_name='activitysoftskill',
            name='soft_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_links', to='profiles.softskill'),
        ),
        migrations.AddField(
            model_name='award',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foreignlang',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_langs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalexp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_exps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='primary_tags',
            field=models.ManyToManyField(blank=True, related_name='primary_activities', to='activity.tag'),
        ),
        migrations.AddField(
            model_name='activity',
            name='secondary_tags',
            field=models.ManyToManyField(blank=True, related_name='secondary_activities', to='activity.tag'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='activities', to='activity.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='activityhardskill',
            unique_together={('activity', 'hard_skill')},
        ),
        migrations.AlterUniqueTogether(
            name='activitysoftskill',
            unique_together={('activity', 'soft_skill')},
        ),
    ]
