# Generated by Django 5.2.4 on 2025-12-01 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_subactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='회�?�명')),
                ('employment_type', models.CharField(blank=True, choices=[('regular', '정규직'), ('contract', '계약직'), ('intern', '인턴'), ('freelancer', '프리랜서')], max_length=20, verbose_name='재직 ?�태')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='직무/부서')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='?�작??')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='종료??')),
                ('is_current', models.BooleanField(default=False, verbose_name='재직 중')),
                ('situation', models.TextField(blank=True, verbose_name='?�황(Situation)')),
                ('task_detail', models.TextField(blank=True, verbose_name='과제(Task)')),
                ('action_detail', models.TextField(blank=True, verbose_name='?�동(Action)')),
                ('result_detail', models.TextField(blank=True, verbose_name='결과(Result)')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='career_attachments/', verbose_name='첨�??�일')),
                ('link_url', models.URLField(blank=True, verbose_name='링크 첨�?/추�?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-period_start'],
            },
        ),
    ]
