# Generated by Django 5.2.4 on 2025-12-01 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignlang',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foreignlang',
            name='exam_grade',
            field=models.CharField(blank=True, max_length=100, verbose_name='점수/등급'),
        ),
        migrations.AddField(
            model_name='foreignlang',
            name='exam_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='시험명'),
        ),
        migrations.AddField(
            model_name='foreignlang',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='링크 추가'),
        ),
        migrations.AddField(
            model_name='foreignlang',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='globalexp',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='진행 중'),
        ),
        migrations.AddField(
            model_name='globalexp',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='링크 추가'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='activity_attachments/', verbose_name='첨부 파일'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='휴지통 여부'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='role',
            field=models.CharField(blank=True, max_length=200, verbose_name='역할 / 담당'),
        ),
        migrations.AlterField(
            model_name='award',
            name='achievement_date',
            field=models.DateField(verbose_name='수상일'),
        ),
        migrations.AlterField(
            model_name='award',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='award_attachments/', verbose_name='첨부 파일'),
        ),
        migrations.AlterField(
            model_name='career',
            name='action_detail',
            field=models.TextField(blank=True, verbose_name='행동(Action)'),
        ),
        migrations.AlterField(
            model_name='career',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='career_attachments/', verbose_name='첨부 파일'),
        ),
        migrations.AlterField(
            model_name='career',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='회사명'),
        ),
        migrations.AlterField(
            model_name='career',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('regular', '정규직'), ('contract', '계약직'), ('intern', '인턴'), ('freelancer', '프리랜서')], max_length=20, verbose_name='재직 형태'),
        ),
        migrations.AlterField(
            model_name='career',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='링크 추가'),
        ),
        migrations.AlterField(
            model_name='career',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='career',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='career',
            name='situation',
            field=models.TextField(blank=True, verbose_name='상황(Situation)'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='achievement_date',
            field=models.DateField(verbose_name='취득일'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='certification_attachments/', verbose_name='첨부 파일'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='만료일'),
        ),
        migrations.AlterField(
            model_name='foreignlang',
            name='achievement_date',
            field=models.DateField(blank=True, null=True, verbose_name='취득일'),
        ),
        migrations.AlterField(
            model_name='foreignlang',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='foreignlang_attachments/', verbose_name='첨부 파일'),
        ),
        migrations.AlterField(
            model_name='foreignlang',
            name='lang_level',
            field=models.CharField(blank=True, choices=[('daily', '일상 회화'), ('business', '비즈니스 회화'), ('native', '원어민 수준')], max_length=20, verbose_name='구사 수준'),
        ),
        migrations.AlterField(
            model_name='foreignlang',
            name='lang_name',
            field=models.CharField(max_length=100, verbose_name='언어'),
        ),
        migrations.AlterField(
            model_name='globalexp',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='globalexp_attachments/', verbose_name='첨부 파일'),
        ),
        migrations.AlterField(
            model_name='subactivity',
            name='hard_tools',
            field=models.CharField(blank=True, max_length=255, verbose_name='툴/기술 스택'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='kind',
            field=models.CharField(choices=[('soft', '소프트 스킬'), ('hard', '하드 스킬'), ('job', '직무')], default='soft', max_length=10, verbose_name='구분'),
        ),
    ]
