# Generated by Django 5.2.4 on 2025-12-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_foreignlang_created_at_foreignlang_exam_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='issuer',
            field=models.CharField(blank=True, max_length=200, verbose_name='주관·수여 기관'),
        ),
        migrations.AddField(
            model_name='award',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='링크 추가'),
        ),
        migrations.AddField(
            model_name='certification',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='링크 추가'),
        ),
        migrations.AlterField(
            model_name='award',
            name='awards_grade',
            field=models.CharField(blank=True, max_length=100, verbose_name='수상 내역'),
        ),
        migrations.AlterField(
            model_name='award',
            name='awards_name',
            field=models.CharField(max_length=200, verbose_name='공모전·대회명'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuer',
            field=models.CharField(blank=True, max_length=200, verbose_name='발급 기관'),
        ),
    ]
