# Generated by Django 5.2.4 on 2025-08-29 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_reset_soft_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='design_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='dev_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='learned',
            field=models.TextField(blank=True, verbose_name='배운 점'),
        ),
        migrations.AddField(
            model_name='activity',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='링크 첨부'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organization',
            field=models.CharField(blank=True, max_length=120, verbose_name='소속 팀/회사'),
        ),
        migrations.AddField(
            model_name='activity',
            name='plan_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='primary_tags',
            field=models.ManyToManyField(blank=True, related_name='primary_activities', to='activity.tag'),
        ),
        migrations.AddField(
            model_name='activity',
            name='secondary_tags',
            field=models.ManyToManyField(blank=True, related_name='secondary_activities', to='activity.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='kind',
            field=models.CharField(choices=[('soft', '소프트'), ('hard', '하드'), ('job', '직무')], default='soft', max_length=10, verbose_name='속성'),
        ),
        migrations.CreateModel(
            name='ActivityRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='역할명')),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='activity.activity')),
            ],
        ),
    ]
