# Generated by Django 5.2.4 on 2025-09-29 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_activity_design_count_activity_dev_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards_name', models.CharField(max_length=200, verbose_name='수상명')),
                ('awards_grade', models.CharField(blank=True, max_length=100, verbose_name='등급/수상내역')),
                ('achievement_date', models.DateField(verbose_name='수상일자')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='award_attachments/', verbose_name='첨부파일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200, verbose_name='자격증명')),
                ('achievement_date', models.DateField(verbose_name='취득일자')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='만료일자')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='발급기관')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='certification_attachments/', verbose_name='첨부파일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
