# Generated by Django 5.2.4 on 2025-11-17 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_activity_design_count_activity_dev_count_and_more'),
        ('profiles', '0006_hardskill_jobcategory_softskill_jobrole_job_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='board_order',
            field=models.PositiveIntegerField(default=0, verbose_name='보드 정렬'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제 여부'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('in_progress', '진행 중'), ('highlight', '주요 스펙'), ('completed', '완료')], default='in_progress', max_length=20, verbose_name='보드 상태'),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards_name', models.CharField(max_length=200, verbose_name='수상명')),
                ('awards_grade', models.CharField(blank=True, max_length=100, verbose_name='등급/수상내역')),
                ('achievement_date', models.DateField(verbose_name='수상일자')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='award_attachments/', verbose_name='첨부파일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200, verbose_name='자격증명')),
                ('achievement_date', models.DateField(verbose_name='취득일자')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='만료일자')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='발급기관')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='certification_attachments/', verbose_name='첨부파일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForeignLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=100, verbose_name='언어명')),
                ('lang_level', models.CharField(max_length=50, verbose_name='수준')),
                ('achievement_date', models.DateField(blank=True, null=True, verbose_name='취득일자')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='foreignlang_attachments/', verbose_name='첨부파일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_langs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_category', models.CharField(max_length=100, verbose_name='경험 카테고리')),
                ('nation', models.CharField(max_length=100, verbose_name='국가')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('language', models.CharField(blank=True, max_length=100, verbose_name='사용 언어')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='globalexp_attachments/', verbose_name='첨부파일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_exps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityHardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('level_description', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hard_skill_links', to='activity.activity')),
                ('hard_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_links', to='profiles.hardskill')),
            ],
            options={
                'unique_together': {('activity', 'hard_skill')},
            },
        ),
        migrations.CreateModel(
            name='ActivitySoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('level_description', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_skill_links', to='activity.activity')),
                ('soft_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_links', to='profiles.softskill')),
            ],
            options={
                'unique_together': {('activity', 'soft_skill')},
            },
        ),
    ]
