# Generated by Django 5.2.4 on 2025-09-29 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_award_certification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=100, verbose_name='언어명')),
                ('lang_level', models.CharField(max_length=50, verbose_name='수준')),
                ('achievement_date', models.DateField(blank=True, null=True, verbose_name='취득일자')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='foreignlang_attachments/', verbose_name='첨부파일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_langs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_category', models.CharField(max_length=100, verbose_name='경험 카테고리')),
                ('nation', models.CharField(max_length=100, verbose_name='국가')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('language', models.CharField(blank=True, max_length=100, verbose_name='사용 언어')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='globalexp_attachments/', verbose_name='첨부파일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_exps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
