# Generated by Django 5.2.4 on 2025-10-27 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_foreignlang_globalexp'),
        ('profiles', '0005_hardskill_jobcategory_softskill_jobrole_job_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityHardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('level_description', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hard_skill_links', to='activity.activity')),
                ('hard_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_links', to='profiles.hardskill')),
            ],
            options={
                'unique_together': {('activity', 'hard_skill')},
            },
        ),
        migrations.CreateModel(
            name='ActivitySoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('level_description', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_skill_links', to='activity.activity')),
                ('soft_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_links', to='profiles.softskill')),
            ],
            options={
                'unique_together': {('activity', 'soft_skill')},
            },
        ),
    ]
