# Generated by Django 5.2.4 on 2025-08-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_bio_user_social_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='user',
            name='github_linked',
            field=models.BooleanField(default=False, verbose_name='깃허브 연동 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='직무'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('student', '학생'), ('junior', '신입'), ('senior', '경력')], max_length=10, verbose_name='레벨'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='user.skill'),
        ),
    ]
