# Generated by Django 5.2.4 on 2025-11-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='프로젝트명')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('position', models.CharField(choices=[('leader', '팀장'), ('member', '팀원'), ('individual', '개인')], default='member', max_length=20, verbose_name='직책')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_line', models.CharField(max_length=255, verbose_name='컨셉 라인')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activities', models.ManyToManyField(blank=True, related_name='portfolios', to='activity.activity', verbose_name='활동 목록')),
            ],
        ),
    ]
