# Generated by Django 5.2.4 on 2025-07-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='activity.activity', verbose_name='활동 목록'),
        ),
    ]
