# Generated by Django 5.2.4 on 2025-10-27 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_activityhardskill_activitysoftskill'),
        ('portfolio', '0002_portfolio_activities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='프로젝트명')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('position', models.CharField(choices=[('leader', '팀장'), ('member', '팀원'), ('individual', '개인')], default='member', max_length=20, verbose_name='직책')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activities', models.ManyToManyField(blank=True, related_name='projects', to='activity.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.projectcategory')),
            ],
            options={
                'ordering': ['-updated_at', '-period_start'],
            },
        ),
    ]
