# Generated by Django 5.2.4 on 2025-12-19 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='selected_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='선택 태그'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='strengths',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='강점'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='포트폴리오 제목'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='work_style',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='업무 스타일'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='concept_line',
            field=models.CharField(blank=True, max_length=255, verbose_name='컨셉 라인'),
        ),
    ]
