# Generated by Django 5.2.4 on 2025-11-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_answer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('article', '정보글'), ('question', '질문'), ('review', '후기'), ('retro', '회고록')], default='article', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('visibility', models.CharField(blank=True, choices=[('public', '공개'), ('private', '비공개')], default='public', max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Retro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retro_type', models.CharField(choices=[('KPT', 'Keep-Problem-Try'), ('AAR', 'After Action Review')], max_length=10)),
                ('date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('mood', models.PositiveSmallIntegerField(default=3)),
                ('keep', models.TextField(blank=True, null=True)),
                ('problem', models.TextField(blank=True, null=True)),
                ('try_field', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('fact', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
