# Generated by Django 5.2.4 on 2025-09-29 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_post_options_remove_post_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Retro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retro_type', models.CharField(choices=[('KPT', 'Keep-Problem-Try'), ('AAR', 'After Action Review')], max_length=10)),
                ('date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('mood', models.PositiveSmallIntegerField(default=3)),
                ('keep', models.TextField(blank=True, null=True)),
                ('problem', models.TextField(blank=True, null=True)),
                ('try_field', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('fact', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retro', to='community.post')),
            ],
        ),
    ]
